version: '3.4'

services:
  album-backend:
    image: album-backend
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8888
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]